spring.application.name=vacas
spring.datasource.url=jdbc:postgresql://localhost:5432/vacas
spring.datasource.username=${BD_USER}
spring.datasource.password=${BD_PASS}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

spring.flyway.enabled=false

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000