/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.44
 * Generated at: 2025-08-26 13:02:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;

public final class table_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\" />\n");
      out.write("  <title>");
      out.print(request.getAttribute("title"));
      out.write("</title>\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/base.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write(" <div class=\"container\">\n");
      out.write("  <h2>");
      out.print(request.getAttribute("title"));
      out.write("</h2>\n");
      out.write("\n");

  // flag que define si se muestra el control de "limit"
  boolean supportsLimit = false;
  Object flag = request.getAttribute("supportsLimit");
  if (flag instanceof Boolean) supportsLimit = (Boolean) flag;
  
  
  //flag que define si se muestra el control de "id"
  boolean supportsId = false;
  Object si = request.getAttribute("supportsId");
  if (si instanceof Boolean) supportsId = (Boolean) si;

  // valor de limit (si aplica)
  String limitParam = request.getParameter("limit");
  String limitValue = (limitParam == null || limitParam.isBlank()) ? "10" : limitParam;
  
 //valor de id (si aplica)
  String idParam = request.getParameter("id");
  String idValue = (idParam == null || idParam.isBlank())
      ? (request.getAttribute("currentId") == null ? "" : String.valueOf(request.getAttribute("currentId")))
      : idParam;

      out.write("\n");
      out.write("\n");
      out.write("  <div class=\"actions\">\n");
      out.write("    <form method=\"get\">\n");
      out.write("        ");
 if (supportsId) { 
      out.write("\n");
      out.write("        <label>ID factura:\n");
      out.write("          <input type=\"number\" name=\"id\" min=\"1\" value=\"");
      out.print( idValue );
      out.write("\" />\n");
      out.write("        </label>\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("      ");
 if (supportsLimit) { 
      out.write("\n");
      out.write("        <label>Límite:\n");
      out.write("          <input type=\"number\" name=\"limit\" min=\"1\" value=\"");
      out.print( limitValue );
      out.write("\"/>\n");
      out.write("        </label>\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("      ");
 if (supportsId || supportsLimit) { 
      out.write("\n");
      out.write("        <button type=\"submit\">Aplicar</button>\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("      \n");
      out.write("      <a href=\"");
      out.print(request.getContextPath());
      out.write("/\">Volver al menú</a>\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write("\n");

  List<Map<String,Object>> data = (List<Map<String,Object>>) request.getAttribute("data");
  if (data == null || data.isEmpty()) {

      out.write("\n");
      out.write("  <p>No hay datos para mostrar.</p>\n");

  } else {
    Map<String,Object> first = data.get(0);

      out.write("\n");
      out.write("  <div class=\"table-scroll\">\n");
      out.write("    <table>\n");
      out.write("      <thead>\n");
      out.write("        <tr>\n");
      out.write("          <th>Nro</th>\n");
      out.write("  ");

        for (String k : first.keySet()) {
  
      out.write("        <th>");
      out.print(k);
      out.write("</th>\n");
      out.write("  ");

        }
  
      out.write("\n");
      out.write("        </tr>\n");
      out.write("      </thead>\n");
      out.write("      <tbody>\n");
      out.write("  ");

        int nro = 1;
        for (Map<String,Object> row : data) {
  
      out.write("      <tr>\n");
      out.write("          <td>");
      out.print(nro++);
      out.write("</td>\n");
      out.write("  ");

          for (Object v : row.values()) {
  
      out.write("        <td>");
      out.print( v );
      out.write("</td>\n");
      out.write("  ");

          }
  
      out.write("      </tr>\n");
      out.write("  ");

        }
  
      out.write("\n");
      out.write("      </tbody>\n");
      out.write("    </table>\n");
      out.write("  </div>\n");

  }

      out.write("\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
