/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.44
 * Generated at: 2025-08-26 13:02:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\" />\n");
      out.write("  <title>Market — Menú</title>\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/base.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"grid\">\n");
      out.write("  <h1>Market — Menú de reportes y formularios</h1>\n");
      out.write("  <p class=\"muted\">Selecciona un reporte o un formulario.</p>\n");
      out.write("    <!-- Reportes -->\n");
      out.write("    <div class=\"card\">\n");
      out.write("      <h2>Reportes (Tops)</h2>\n");
      out.write("      <ul>\n");
      out.write("        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/reports/top-clientes\">Top clientes por cantidad de facturas</a></li>\n");
      out.write("        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/reports/top-gasto\">Top clientes que más gastaron</a></li>\n");
      out.write("        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/reports/top-monedas\">Top monedas más utilizadas</a></li>\n");
      out.write("        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/reports/top-proveedores\">Top proveedores por cantidad de productos</a></li>\n");
      out.write("        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/reports/productos-mas\">Productos más vendidos</a></li>\n");
      out.write("        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/reports/productos-menos\">Productos menos vendidos</a></li>\n");
      out.write("        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/reports/factura-detalle?id=1\">Detalle de una factura </a></li>\n");
      out.write("        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/reports/facturas-orden-total\">Facturas ordenadas por total</a></li>\n");
      out.write("        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/reports/iva-10\">IVA 10% por factura</a></li>\n");
      out.write("      </ul>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Formularios -->\n");
      out.write("   <div class=\"card\">\n");
      out.write("      <h2>Formularios (ABM)</h2>\n");
      out.write("      <ul>\n");
      out.write("        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/forms/cliente/new\">Nuevo cliente</a></li>\n");
      out.write("        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/forms/producto/new\">Nuevo producto</a></li>\n");
      out.write("        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/forms/proveedor/new\">Nuevo proveedor</a></li>\n");
      out.write("       <!-- <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/forms/factura/new\">Nueva factura (con detalles)</a></li>-->\n");
      out.write("      </ul>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <!--<p class=\"muted\">Debug: <a href=\"");
      out.print(request.getContextPath());
      out.write("/db/health\">Probar conexión a BD</a></p>-->\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
